version: "3"

services:
  web:
    image: posox/brbl-stats:latest
    networks:
      - backend
      - frontend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db/postgres"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    ports:
      - "8000:8000"
    command: gunicorn -b 0.0.0.0 brbl_stats.api:app

  engine:
    image: posox/brbl-stats:latest
    networks:
      - backend
    environment:
      DATABASE_URL: "postgres://postgres:password@db/postgres"
      IG_USERNAME: "${IG_USERNAME}"
      IG_PASSWORD: "${IG_PASSWORD}"
      IG_CHECKPOINT: "${IG_CHECKPOINT}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: python3 -m brbl_stats.engine

  db:
    image: postgres:11
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:
